namespace NanaZip.Modern
{
    // CuinZip P1-2: 状态栏信息层级重整。
    runtimeclass StatusBar : Windows.UI.Xaml.Controls.Control
    {
        StatusBar();

        String TextPrimary;
        static Windows.UI.Xaml.DependencyProperty TextPrimaryProperty{ get; };

        String TextArchive;
        static Windows.UI.Xaml.DependencyProperty TextArchiveProperty{ get; };
    }
}
