# Integration tests against the real archive engine. All fixtures stay in Output.
param([Parameter(Mandatory = $true)][string]$BinDir)
$ErrorActionPreference = 'Stop'
$repo = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$console = Join-Path (Resolve-Path -LiteralPath $BinDir).Path 'NanaZip.Universal.Console.exe'
if (-not (Test-Path -LiteralPath $console)) { throw "Missing CLI: $console" }
$testRoot = Join-Path $repo 'Output\Tests'
# Do not follow an output junction outside this repository.
foreach ($part in @((Join-Path $repo 'Output'), $testRoot)) {
    if ((Test-Path -LiteralPath $part) -and ((Get-Item -LiteralPath $part).Attributes -band [IO.FileAttributes]::ReparsePoint)) {
        throw "Test output must not be a reparse point: $part"
    }
}
$work = Join-Path $testRoot ('roundtrip-' + [guid]::NewGuid().ToString('N'))
$null = New-Item -ItemType Directory -Path (Join-Path $work 'source\nested folder'), (Join-Path $work 'source\empty folder'), (Join-Path $work 'temp')
$source = Join-Path $work 'source'
[IO.File]::WriteAllText((Join-Path $source '说明 中文.txt'), "CuinZip 中文与空格路径 roundtrip`r`n", [Text.Encoding]::UTF8)
[IO.File]::WriteAllBytes((Join-Path $source 'zero.bin'), [byte[]]@())
$random = [Random]::new(314159)
$bytes = [byte[]]::new(65536)
$random.NextBytes($bytes)
[IO.File]::WriteAllBytes((Join-Path $source 'nested folder\binary.dat'), $bytes)
$oldTemp = $env:TEMP
$oldTmp = $env:TMP
$passed = 0
function Invoke-Archive([string[]]$CliArguments, [bool]$ExpectSuccess = $true) {
    # Every argument here is generated by this test, with no embedded quotes or
    # trailing backslash. Run directly, without a shell, and drain both pipes.
    $info = [Diagnostics.ProcessStartInfo]::new()
    $info.FileName = $console
    $info.WorkingDirectory = $work
    $info.UseShellExecute = $false
    $info.CreateNoWindow = $true
    $info.RedirectStandardOutput = $true
    $info.RedirectStandardError = $true
    $info.Arguments = ($CliArguments | ForEach-Object { '"' + $_ + '"' }) -join ' '
    $process = [Diagnostics.Process]::new()
    $process.StartInfo = $info
    try {
        $null = $process.Start()
        $stdout = $process.StandardOutput.ReadToEndAsync()
        $stderr = $process.StandardError.ReadToEndAsync()
        if (-not $process.WaitForExit(30000)) { $process.Kill(); throw 'Archive command timed out' }
        $output = $stdout.Result + $stderr.Result
        $code = $process.ExitCode
        if (($ExpectSuccess -and $code -ne 0) -or (-not $ExpectSuccess -and $code -eq 0)) {
            throw "Unexpected exit $code for $($CliArguments[0]): $output"
        }
        return $output
    } finally { $process.Dispose() }
}
function Assert-Roundtrip([string]$Destination) {
    $original = @(Get-ChildItem -LiteralPath $source -File -Recurse)
    $extracted = @(Get-ChildItem -LiteralPath (Join-Path $Destination 'source') -File -Recurse)
    if ($extracted.Count -ne $original.Count) { throw 'Extracted file count differs' }
    foreach ($file in $original) {
        $relative = $file.FullName.Substring($source.Length + 1)
        $target = Join-Path $Destination ('source\' + $relative)
        if ((Get-FileHash -LiteralPath $file.FullName).Hash -ne (Get-FileHash -LiteralPath $target).Hash) {
            throw "Content mismatch: $relative"
        }
    }
    if (-not (Test-Path -LiteralPath (Join-Path $Destination 'source\empty folder') -PathType Container)) {
        throw 'Empty directory was lost'
    }
}
try {
    $env:TEMP = Join-Path $work 'temp'
    $env:TMP = $env:TEMP
    $cases = @(
        @{ Name='zip'; Format='zip'; Extra=@(); Password=@() },
        @{ Name='7z'; Format='7z'; Extra=@(); Password=@() },
        @{ Name='zip-aes'; Format='zip'; Extra=@('-pFixture123', '-mem=AES256'); Password=@('-pFixture123') },
        @{ Name='7z-aes'; Format='7z'; Extra=@('-pFixture123', '-mhe=on'); Password=@('-pFixture123') },
        @{ Name='7z-split'; Format='7z'; Extra=@('-v10k'); Password=@() }
    )
    foreach ($case in $cases) {
        $archive = Join-Path $work ($case.Name + '.' + $case.Format)
        $null = Invoke-Archive (@('a', ('-t' + $case.Format), '-mx=5', $archive, $source) + $case.Extra)
        if ($case.Name -eq '7z-split') {
            if (@(Get-ChildItem -LiteralPath $work -Filter '7z-split.7z.*').Count -lt 2) { throw 'Real multi-volume archive not created' }
            $archive += '.001'
        }
        $null = Invoke-Archive (@('t', $archive) + $case.Password)
        $out = Join-Path $work ('out-' + $case.Name)
        $null = Invoke-Archive (@('x', '-y', ('-o' + $out), $archive) + $case.Password)
        Assert-Roundtrip $out
        if ($case.Format -eq 'zip') {
            # Interoperability: plain ZIP must also be readable by Windows/.NET.
            $signature = [IO.File]::ReadAllBytes($archive)
            if ($signature[0] -ne 0x50 -or $signature[1] -ne 0x4b) { throw 'ZIP extension contains a different format' }
        }
        if ($case.Name -eq 'zip') {
            Add-Type -AssemblyName System.IO.Compression.FileSystem
            $windowsOut = Join-Path $work 'out-windows-zip'
            [IO.Compression.ZipFile]::ExtractToDirectory($archive, $windowsOut)
            Assert-Roundtrip $windowsOut
            Write-Output 'PASS Windows/.NET ZIP interoperability'
            $passed++
            [IO.File]::WriteAllText((Join-Path $out 'source\说明 中文.txt'), 'old contents')
            $null = Invoke-Archive @('x', '-y', ('-o' + $out), $archive)
            Assert-Roundtrip $out
            Write-Output 'PASS overwrite restores exact contents'
            $passed++
        }
        Write-Output "PASS $($case.Name): Unicode, spaces, nested files, zero-byte file, empty directory, SHA-256"
        $passed++
    }
    $null = Invoke-Archive @('t', '-pWrongFixture', (Join-Path $work '7z-aes.7z')) $false
    Write-Output 'PASS wrong password returns failure'
    $passed++
    $null = Invoke-Archive @('x', '-y', ('-o' + (Join-Path $work 'missing-out')), (Join-Path $work 'missing.zip')) $false
    Write-Output 'PASS missing archive returns failure'
    $passed++
    [IO.File]::WriteAllBytes((Join-Path $work 'broken.zip'), [byte[]](0x50,0x4b,3,4,0,1,2,3))
    $null = Invoke-Archive @('t', (Join-Path $work 'broken.zip')) $false
    Write-Output 'PASS corrupt archive returns failure'
    $passed++
    Write-Output "Archive integration: $passed PASS; artifacts: $work"
} finally {
    $env:TEMP = $oldTemp
    $env:TMP = $oldTmp
}
